name: islami
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  animated_custom_dropdown: 3.1.1
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  flutter_lints: ^4.0.0



flutter:
  generate: true


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/files/
    - assets/files/hadeth/




  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri/ElMessiri-Bold.ttf
        - asset: assets/fonts/ElMessiri/ElMessiri-Medium.ttf
        - asset: assets/fonts/ElMessiri/ElMessiri-Regular.ttf
        - asset: assets/fonts/ElMessiri/ElMessiri-SemiBold.ttf

    - family: Reem-kufi
      fonts:
        - asset: assets/fonts/Reem-kufi/ReemKufiFun-Regular.ttf
        - asset: assets/fonts/Reem-kufi/ReemKufiFun-Bold.ttf
        - asset: assets/fonts/Reem-kufi/ReemKufiFun-Medium.ttf
        - asset: assets/fonts/Reem-kufi/ReemKufiFun-SemiBold.ttf


